### ISSUE TITLE
Hot Reload

### ISSUE THREAD

**Issue by vietduc1441** [mendix/pluggable-widgets-generator#44]
I am experimenting with widget generated by yo.
I think the boiler plate is using react hot reloader.
But if i change text in my component (now it is "Hello world") i see the whole web page is reloaded.
While it saves me an F5 but is it really "hot" reload.
Or do i have to have some additional step?

**Comment by diego-antonelli** [comment]
Hi @vietduc1441 indeed we noticed we are not using full functionalities of hot reload. It will be implemented in next version, we have a technical internal issue around this and we are still trying to fix it in Mendix Studio Pro. So I will close this ticket because:
1 - We already have a Jira task internally
2 - This repo was archived, so please keep tracking in https://github.com/mendix/widgets-resources
